// Generates SQL to seed local D1 with test data (clients, projects, invoices, tickets).
// Not run automatically — output is piped into `wrangler d1 execute --local`.
import { randomUUID, webcrypto } from "node:crypto";

const PASSWORD_ITERATIONS = 100_000;

function toBase64(bytes) {
  return Buffer.from(bytes).toString("base64");
}

async function hashPassword(password) {
  const salt = webcrypto.getRandomValues(new Uint8Array(16));
  const keyMaterial = await webcrypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    "PBKDF2",
    false,
    ["deriveBits"]
  );
  const bits = await webcrypto.subtle.deriveBits(
    { name: "PBKDF2", hash: "SHA-256", salt, iterations: PASSWORD_ITERATIONS },
    keyMaterial,
    256
  );
  return `pbkdf2$${PASSWORD_ITERATIONS}$${toBase64(salt)}$${toBase64(new Uint8Array(bits))}`;
}

function esc(value) {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return String(value);
  return `'${String(value).replace(/'/g, "''")}'`;
}

function insert(table, cols, rows) {
  return rows
    .map((row) => `INSERT INTO ${table} (${cols.join(", ")}) VALUES (${row.map(esc).join(", ")});`)
    .join("\n");
}

const now = Date.now();
const day = 86_400_000;

const clients = [
  { company: "Riverside Roasters", contact: "Maya Chen", email: "maya@riversideroasters.test", phone: "419-555-0142" },
  { company: "Harbor Light Legal", contact: "Owen Baptiste", email: "owen@harborlightlegal.test", phone: "419-555-0198" },
];

const userRows = [];
const clientRows = [];
const projectRows = [];
const featureRows = [];
const invoiceRows = [];
const ticketRows = [];
const messageRows = [];

let out = [];
out.push("-- Local dev test data. Generated by scripts/seed-local.mjs — do not run against remote.");

for (const c of clients) {
  const userId = randomUUID();
  const clientId = randomUUID();
  const passwordHash = await hashPassword("test-password-123");

  userRows.push([userId, c.email, passwordHash, "client", 1, now]);
  clientRows.push([clientId, userId, c.company, c.contact, c.phone, now]);

  const projectId = randomUUID();
  projectRows.push([
    projectId,
    clientId,
    `${c.company} Website Refresh`,
    "Redesign and CMS migration.",
    "in_progress",
    now - 14 * day,
    now + 30 * day,
    now - 14 * day,
    now,
  ]);

  featureRows.push(
    [randomUUID(), projectId, "Homepage hero redesign", null, "done", now - 10 * day, now - 2 * day],
    [randomUUID(), projectId, "Contact form + spam filtering", null, "in_progress", now - 5 * day, now],
    [randomUUID(), projectId, "Blog/CMS integration", null, "backlog", now, now]
  );

  invoiceRows.push(
    [randomUUID(), clientId, "Discovery & design phase", 250000, "paid", now - 20 * day, now - 6 * day, now - 8 * day, now - 20 * day, now - 8 * day],
    [randomUUID(), clientId, "Development phase — milestone 1", 400000, "sent", now - 3 * day, now + 11 * day, null, now - 3 * day, now - 3 * day]
  );

  ticketRows.push([randomUUID(), clientId, "Can we change the header font?", "open", "normal", now - 2 * day, now - 1 * day]);
  const lastTicketId = ticketRows[ticketRows.length - 1][0];
  messageRows.push([randomUUID(), lastTicketId, userId, "Loving the progress so far — could we try a different font in the header?", now - 2 * day]);
}

out.push(insert("users", ["id", "email", "password_hash", "role", "is_active", "created_at"], userRows));
out.push(insert("clients", ["id", "user_id", "company_name", "contact_name", "phone", "created_at"], clientRows));
out.push(
  insert(
    "projects",
    ["id", "client_id", "name", "description", "status", "start_date", "target_date", "created_at", "updated_at"],
    projectRows
  )
);
out.push(
  insert("project_features", ["id", "project_id", "title", "description", "status", "created_at", "updated_at"], featureRows)
);
out.push(
  insert(
    "invoices",
    ["id", "client_id", "description", "amount_cents", "status", "issued_date", "due_date", "paid_date", "created_at", "updated_at"],
    invoiceRows
  )
);
out.push(insert("tickets", ["id", "client_id", "subject", "status", "priority", "created_at", "updated_at"], ticketRows));
out.push(insert("ticket_messages", ["id", "ticket_id", "author_user_id", "body", "created_at"], messageRows));

console.log(out.join("\n\n"));
console.error(`\nTest client logins (password: test-password-123):\n${clients.map((c) => `  ${c.email}`).join("\n")}`);
